[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python manage.py migrate && gunicorn licenseexpirary.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/healthcheck/"
healthcheckTimeout = 300
releaseCommand = "python manage.py migrate"
restartPolicyType = "ON_FAILURE"
