# Generated by Django 5.2 on 2025-05-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='back_photo',
            field=models.FileField(blank=True, null=True, upload_to='license_photos/'),
        ),
        migrations.AlterField(
            model_name='license',
            name='front_photo',
            field=models.FileField(blank=True, null=True, upload_to='license_photos/'),
        ),
    ]
